In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

# 1. Load the data

In [8]:
circuit_eco = pd.read_csv("data/circuit_economics.csv")
construction = pd.read_csv("data/constructor_finances.csv")
standing = pd.read_csv("data/driver_standings.csv")
business = pd.read_csv("data/f1_business.csv")
results = pd.read_csv("data/race_results.csv")

# 2. Review the data

In [9]:
circuit_eco.head()

,season,grand_prix,circuit,country_iso3,region,hosting_fee_usd_m_est,weekend_attendance_k,debut_year,is_street_circuit,is_new_circuit_post_2020
0,2010,Bahrain,Sakhir,BHR,Middle East,38.5,97,2004,0,0
1,2012,Bahrain,Sakhir,BHR,Middle East,35.8,100,2004,0,0
2,2013,Bahrain,Sakhir,BHR,Middle East,34.6,94,2004,0,0
3,2014,Bahrain,Sakhir,BHR,Middle East,35.1,96,2004,0,0
4,2015,Bahrain,Sakhir,BHR,Middle East,34.2,94,2004,0,0

In [11]:
construction.head()

,season,team_name,country_iso3,operating_budget_usd_m,sponsorship_revenue_usd_m,prize_money_usd_m,total_revenue_usd_m,in_cost_cap_era,cost_cap_limit_usd_m,is_constructors_champion
0,2010,Mercedes,DEU,270.0,86.2,112.6,198.8,0,NaN,0
1,2011,Mercedes,DEU,320.5,100.2,118.4,218.6,0,NaN,0
2,2012,Mercedes,DEU,308.3,102.4,130.4,232.9,0,NaN,0
3,2013,Mercedes,DEU,356.9,126.9,158.6,285.6,0,NaN,0
4,2014,Mercedes,DEU,339.4,128.8,173.6,302.3,0,NaN,1

In [12]:
standing.head()

,season,championship_position,driver_name,country_iso3,total_points,wins,poles,podiums_est,is_world_champion
0,2010,1,Sebastian Vettel,DEU,256,5,10,9,1
1,2010,2,Fernando Alonso,ESP,252,5,2,9,0
2,2010,3,Mark Webber,AUS,242,4,5,8,0
3,2010,4,Lewis Hamilton,GBR,240,3,1,7,0
4,2010,5,Jenson Button,GBR,214,2,0,5,0

In [13]:
business.head()

,season,total_revenue_usd_m,race_promotion_fees_usd_m,broadcast_media_usd_m,sponsorship_usd_m,other_revenue_usd_m,is_liberty_media_era,drive_to_survive_viewers_m_est,us_avg_race_viewers_m,global_avg_race_viewers_m
0,2010,1108.0,399.0,377.0,177.0,155.0,0,0,0.55,70.0
1,2011,1265.0,455.0,430.0,202.0,177.0,0,0,0.55,71.5
2,2012,1377.0,496.0,468.0,220.0,193.0,0,0,0.55,73.0
3,2013,1509.0,543.0,513.0,241.0,211.0,0,0,0.55,74.5
4,2014,1728.0,622.0,588.0,276.0,242.0,0,0,0.55,76.0

In [14]:
results.head()

,race_id,season,round_number,race_date,grand_prix,circuit,country_iso3,region,pole_position,winner,podium_p2,podium_p3,fastest_lap_driver,safety_car_periods,is_sprint_weekend
0,R001,2010,1,2010-03-21,Bahrain,Sakhir,BHR,Middle East,Robert Kubica,Lewis Hamilton,Mark Webber,Oscar Piastri,Oscar Piastri,0,0
1,R002,2010,2,2010-03-15,Australia,Albert Park,AUS,Oceania,Sebastian Vettel,Fernando Alonso,Mark Webber,Valtteri Bottas,Daniel Ricciardo,1,0
2,R003,2010,3,2010-04-10,Malaysia,Sepang,MYS,Asia,Sebastian Vettel,Jenson Button,Lando Norris,Oscar Piastri,Lando Norris,1,0
3,R004,2010,4,2010-04-03,China,Shanghai,CHN,Asia,Sebastian Vettel,Fernando Alonso,Lewis Hamilton,Daniel Ricciardo,Fernando Alonso,0,0
4,R005,2010,5,2010-05-19,Spain,Barcelona,ESP,Europe,Mark Webber,Mark Webber,Lewis Hamilton,Fernando Alonso,Lewis Hamilton,1,0

In [15]:
circuit_eco.isna().sum()

season                      0
grand_prix                  0
circuit                     0
country_iso3                0
region                      0
hosting_fee_usd_m_est       0
weekend_attendance_k        0
debut_year                  0
is_street_circuit           0
is_new_circuit_post_2020    0
dtype: int64

In [16]:
construction.isna().sum()

season                         0
team_name                      0
country_iso3                   0
operating_budget_usd_m         0
sponsorship_revenue_usd_m      0
prize_money_usd_m              0
total_revenue_usd_m            0
in_cost_cap_era                0
cost_cap_limit_usd_m         104
is_constructors_champion       0
dtype: int64

In [17]:
standing.isna().sum()

season                   0
championship_position    0
driver_name              0
country_iso3             0
total_points             0
wins                     0
poles                    0
podiums_est              0
is_world_champion        0
dtype: int64

In [18]:
business.isna().sum()

season                            0
total_revenue_usd_m               0
race_promotion_fees_usd_m         0
broadcast_media_usd_m             0
sponsorship_usd_m                 0
other_revenue_usd_m               0
is_liberty_media_era              0
drive_to_survive_viewers_m_est    0
us_avg_race_viewers_m             0
global_avg_race_viewers_m         0
dtype: int64

In [19]:
results.isna().sum()

race_id               0
season                0
round_number          0
race_date             0
grand_prix            0
circuit               0
country_iso3          0
region                0
pole_position         0
winner                0
podium_p2             0
podium_p3             0
fastest_lap_driver    0
safety_car_periods    0
is_sprint_weekend     0
dtype: int64

In [ ]:
# 3. Explanatory D